name: CI Pipeline - Build, Push, and Update Manifest

on:
  push:
    branches:
      - main # Chỉ chạy khi push lên nhánh 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Generate Image Tag
        id: generate_tag
        # Tạo tag duy nhất cho image, ví dụ: '20251027-a1b2c3d'
        run: echo "TAG_NAME=$(date +%Y%m%d)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ env.TAG_NAME }} # Sử dụng tag duy nhất

      # ----- PHẦN QUAN TRỌNG: CẬP NHẬT MANIFEST REPO -----

      - name: Checkout Manifest Repo
        uses: actions/checkout@v3
        with:
          # Đây là tên của 'manifest-repo'
          repository: your-username/manifest-repo
          # Cần PAT để có quyền push
          token: ${{ secrets.REPO_PAT }}

      - name: Update Image Tag in Deployment
        run: |
          # Sử dụng 'sed' để tìm và thay thế image tag trong file deployment.yaml
          # Đây là cách đơn giản nhất. 
          # Bạn cũng có thể dùng Kustomize hoặc Helm
          sed -i 's|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ env.TAG_NAME }}|' deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add deployment.yaml
          # Chỉ commit nếu có thay đổi
          git commit -m "Update image tag to ${{ env.TAG_NAME }} for my-app" || echo "No changes to commit"
          git push